### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Haggerman** [jezura/firemni_system#1]
Celej login se bude msuet ještě předělat, tohle je dost provizorní verze. 

Možná by se to celý dalo nějak sjednotit -> místo toho, aby se pro každej typ uživatelů hledat login zvlášť, tak to hledat jen pro typ <Person> tímhle způsobem by se ale muselo udělat query, který spojí všechny tabulky s uživateli do jedný a nad tím hledat ten login

**Comment by jezura** [comment]
Vyřešeno, login funguje dobře. Je tam i logout a zobrazení přihlášenýho uživatele.
